In [1]:
import pandas as pd 
import numpy as np

symptoms_diagnosis

In [12]:
df = pd.read_json(r"C:\Users\HP\symptoms_diagnosis_dataset\clean_symptoms_diagnosis_1000.json")

In [13]:
df

,symptoms,diagnosis
0,"Patient reported these symptoms: depression ,h...",personality disorder
1,"Patient reported these symptoms: depression ,d...",attention deficit hyperactivity disorder (adhd)
2,Patient reported these symptoms: abnormal invo...,muscle spasm
3,Patient reported these symptoms: sharp abdomin...,diverticulitis
4,"Patient reported these symptoms: hot flashes ,...",polycystic ovarian syndrome (pcos)
...,...,...
995,"Patient reported these symptoms: fainting ,sha...",intestinal disease
996,Patient reported these symptoms: sharp abdomin...,gastritis
997,Patient reported these symptoms: arm stiffness...,fracture of the arm
998,"Patient reported these symptoms: leg pain ,wri...",tendinitis
999,Patient reported these symptoms: hostile behav...,depression

medquad_cleaned

In [14]:
df= pd.read_json(r"C:\Users\HP\medquad_cleaned.json")

In [15]:
df

,Question,Answer
0,Who is at risk for Lymphocytic Choriomeningiti...,LCMV infections can occur after exposure to fr...
1,What are the symptoms of Lymphocytic Choriomen...,LCMV is most commonly recognized as causing ne...
2,Who is at risk for Lymphocytic Choriomeningiti...,Individuals of all ages who come into contact ...
3,How to diagnose Lymphocytic Choriomeningitis (...,"During the first phase of the disease, the mos..."
4,What are the treatments for Lymphocytic Chorio...,"Aseptic meningitis, encephalitis, or meningoen..."
...,...,...
16402,What are the symptoms of Familial visceral myo...,What are the signs and symptoms of Familial vi...
16403,What is (are) Pseudopelade of Brocq ?,Pseudopelade of Brocq (PBB) is a slowly progre...
16404,What are the symptoms of Pseudopelade of Brocq ?,What are the signs and symptoms of Pseudopelad...
16405,What are the treatments for Pseudopelade of Br...,Is there treatment or a cure for pseudopelade ...
16406,What is (are) Desmoplastic small round cell tu...,"Desmoplastic small round cell tumors (DSRCT), ..."

Medical Meadow

In [18]:
df = pd.read_json(r"C:\Users\HP\Medical Meadow_dataset.json")

In [19]:
df

,input,output,instruction
0,i had what feels like a muscle cramp about an ...,No this is not a symptom of great attack.... i...,"If you are a doctor, please answer the medical..."
1,I woke up this morning feeling the whole room ...,"Hi, Thank you for posting your query. The most...","If you are a doctor, please answer the medical..."
2,My baby has been pooing 5-6 times a day for a ...,Hi... Thank you for consulting in Chat Doctor....,"If you are a doctor, please answer the medical..."
3,my sone has left sided abd pain..lt pelvic and...,"Hi. If there is no relief, it is mandatory to ...","If you are a doctor, please answer the medical..."
4,My one year old son was bit in face by a pit b...,Hi.the diarrhea is due to Chat Doctor. Freque...,"If you are a doctor, please answer the medical..."
...,...,...,...
207403,My 5 year old son has been coughing for a mont...,As you have mentioned in your history that you...,"If you are a doctor, please answer the medical..."
207404,My toes on right foot more than left are numb ...,Hi. The numbness and blue discoloration could ...,"If you are a doctor, please answer the medical..."
207405,"I was diagnosis with pleurisy last Tuesday, an...",Thanks for your question on Chat Doctor. Treat...,"If you are a doctor, please answer the medical..."
207406,hi i have just found out im pregnant after hav...,"HI, Thank you for your query. I understand you...","If you are a doctor, please answer the medical..."
207407,"Within the past few hours, my husband has deve...","Hello, Thank you for posting on Chat Doctor. T...","If you are a doctor, please answer the medical..."

chatdoctor

In [22]:
df = pd.read_json(r"C:\Users\HP\chatdoctor_clean_dataset\chatdoctor_input_output_1000.json")

In [23]:
df

,input,output
0,i had what feels like a muscle cramp about an ...,No this is not a symptom of great attack.... i...
1,I woke up this morning feeling the whole room ...,"Hi, Thank you for posting your query. The most..."
2,My baby has been pooing 5-6 times a day for a ...,Hi... Thank you for consulting in Chat Doctor....
3,my sone has left sided abd pain..lt pelvic and...,"Hi. If there is no relief, it is mandatory to ..."
4,My one year old son was bit in face by a pit b...,Hi.the diarrhea is due to Chat Doctor. Freque...
...,...,...
995,I have a lump or thickening in my labia majora...,"Hello and welcome to Chat Doctor, A painful lu..."
996,Hello. My friend had fever the other day. He t...,"Hello, Your friend can have viral infection th..."
997,yes. im on clomid month 2 and last month by C...,"Hi, I think it can happen in some cycles. Some..."
998,Hi dr. I have undergone an Ivf treatment n hav...,"Hi, Thanks for writing to ChatDoctor . Both th..."
999,"About 2 weeks ago, the gums at the back of my ...","Dear friend you are right, it is natural proce..."

In [33]:
import json
import os 
folder = "symptoms_diagnosis_dataset"
# Load all datasets
with open("medquad_cleaned.json", "r", encoding="utf-8") as f:
    medquad = json.load(f)

with open("chatdoctor_input_output_1000.json", "r", encoding="utf-8") as f:
    chatdoctor = json.load(f)

with open("Medical Meadow_dataset.json", "r", encoding="utf-8") as f:
    medical_meadow = json.load(f)

with open("symptoms_to_diagnosis_1000.json", "r", encoding="utf-8") as f:
    symptoms = json.load(f)

merged_data = []

# 1. MedQuad
for row in medquad:
    merged_data.append({
        "source": "MedQuad",
        "input": row.get("Question", ""),
        "output": row.get("Answer", "")
    })

# 2. Chat Doctor
for row in chatdoctor:
    merged_data.append({
        "source": "ChatDoctor",
        "input": row.get("input", ""),
        "output": row.get("output", "")
    })

# 3. Medical Meadow
for row in medical_meadow:
    text_input = row.get("instruction", "") + " " + row.get("input", "")
    
    merged_data.append({
        "source": "MedicalMeadow",
        "input": text_input.strip(),
        "output": row.get("output", "")
    })

# 4. Symptoms to Diagnosis
for row in symptoms:
    merged_data.append({
        "source": "SymptomsDiagnosis",
        "input": row.get("symptoms", ""),
        "output": row.get("diagnosis", "")
    })

# Save merged dataset
with open("merged_medical_dataset.json", "w", encoding="utf-8") as f:
    json.dump(merged_data, f, indent=4, ensure_ascii=False)

print("Merged successfully")
print("Total rows:", len(merged_data))

Merged successfully
Total rows: 225815

In [35]:
unique_data = []
seen = set()

for row in merged_data:
    pair = (row["input"], row["output"])
    if pair not in seen:
        seen.add(pair)
        unique_data.append(row)

print("After duplicate removal:", len(unique_data))

After duplicate removal: 225135

In [36]:
with open("clean_merged_dataset.json", "w", encoding="utf-8") as f:
    json.dump(unique_data, f, indent=4)

In [30]:
import os
print(os.getcwd())

C:\Users\HP

In [27]:
import os
print(os.listdir())

['.anaconda', '.cache', '.conda', '.condarc', '.continuum', '.dbclient', '.Icecream Photo Editor', '.idlerc', '.ipynb_checkpoints', '.ipython', '.jdks', '.jupyter', '.matplotlib', '.spyder-py3', '.virtual_documents', '.vscode', 'all_slake_images', 'anaconda3', 'AppData', 'Application Data', 'battery-report.html', 'c++ program', 'Chat Doctor.ipynb', 'chatdoctor_1000_dataset', 'chatdoctor_clean_dataset', 'chatdoctor_json_dataset', 'Chat_Docter', 'Chest X .ipynb', 'Chest X-Ray dataset_images.ipynb', 'chest_xray_1000', 'chest_xray_1000_qa.json', 'chest_xray_dataset_json', 'chest_xray_images', 'chest_xray_qa_1000.json', 'Contacts', 'Cookies', 'Data-Driven Forecasting & Peak Demand Prediction.ipynb', 'Documents', 'Downloads', 'Favorites', 'final_slake_images', 'Healthcare Daataset.ipynb', 'IdeaProjects', 'Links', 'Local Settings', 'Medical Meadow', 'Medical Meadow_dataset.json', 'Medical Prescription dataset.ipynb', 'medical_meadow_dataset', 'medical_record_images', 'MedQuad (Medical Question Answering)', 'MedQuad (Medical Question Answering).ipynb', 'MedQuad _Dataset.ipynb', 'medquad_cleaned.csv', 'medquad_cleaned.json', 'Microsoft', 'Music', 'My Documents', 'my-new-folder', 'myenv', 'NetHood', 'New folder', 'New folder (2)', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{53d5786b-a5e0-11f0-9937-ba192aceefa8}.TM.blf', 'NTUSER.DAT{53d5786b-a5e0-11f0-9937-ba192aceefa8}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{53d5786b-a5e0-11f0-9937-ba192aceefa8}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'pemhttpd.exe', 'prescription_1000.csv', 'prescription_1000.json', 'PrintHood', 'PycharmProjects', 'Recent', 'ROCO - Radiology Object in Context.ipynb', 'roco_1000_jpg_images', 'roco_train_images', 'Saved Games', 'saved_images', 'ScStore', 'Searches', 'SendTo', 'SLAKEDATA_IMAGES.ipynb', 'slake_images', 'Sql-Server-to-postgres-migration', 'Start Menu', 'symptoms_diagnosis_dataset', 'symptom_dataset', 'Templates', 'unique_vqa_images', 'Untitled Folder', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Untitled4.ipynb', 'Videos', 'VQA-RAD_IMAGES.ipynb', 'vqa_rad_images', 'vqa_rad_jpg_images', 'WPS Cloud Files']

In [37]:
df = pd.read_json(r"C:\Users\HP\clean_merged_dataset.json")

In [38]:
df

,source,input,output
0,MedQuad,Who is at risk for Lymphocytic Choriomeningiti...,LCMV infections can occur after exposure to fr...
1,MedQuad,What are the symptoms of Lymphocytic Choriomen...,LCMV is most commonly recognized as causing ne...
2,MedQuad,Who is at risk for Lymphocytic Choriomeningiti...,Individuals of all ages who come into contact ...
3,MedQuad,How to diagnose Lymphocytic Choriomeningitis (...,"During the first phase of the disease, the mos..."
4,MedQuad,What are the treatments for Lymphocytic Chorio...,"Aseptic meningitis, encephalitis, or meningoen..."
...,...,...,...
225130,SymptomsDiagnosis,,floaters
225131,SymptomsDiagnosis,,shingles (herpes zoster)
225132,SymptomsDiagnosis,,drug abuse (cocaine)
225133,SymptomsDiagnosis,,chronic pancreatitis
225134,SymptomsDiagnosis,,lichen simplex

In [39]:
print(df.columns)

Index(['source', 'input', 'output'], dtype='object')

In [40]:
import pandas as pd

df = pd.read_json("merged_medical_dataset.json")

symptom_rows = df[df["source"] == "SymptomsDiagnosis"]

print(symptom_rows.head())

                   source input  \
224815  SymptomsDiagnosis
224816  SymptomsDiagnosis
224817  SymptomsDiagnosis
224818  SymptomsDiagnosis
224819  SymptomsDiagnosis

                                                 output
224815                             personality disorder
224816  attention deficit hyperactivity disorder (adhd)
224817                                     muscle spasm
224818                                   diverticulitis
224819               polycystic ovarian syndrome (pcos)